Repository Happyr/Doctrine-Specification, pull requests merged in 2019-06, with the labels that each got.

#199 Fix return type of BaseSpecification::getSpec()
  src/BaseSpecification.php
Labels: bug

#198 Use shields.io for badges
  README.md
Labels: feature

#204 Change bitwise queries and remove unsupported operations
  src/Operand/Bitwise.php
  tests/Operand/BitAndSpec.php
  tests/Operand/BitLeftShiftSpec.php
  tests/Operand/BitNotSpec.php
  tests/Operand/BitOrSpec.php
  tests/Operand/BitRightShiftSpec.php
  tests/Operand/BitXorSpec.php
  tests/SpecSpec.php
Labels: BC Break, feature

#194 Create Having query modifiers
  src/Query/Having.php
  src/Spec.php
  src/Specification/Having.php
  tests/Query/HavingSpec.php
Labels: feature
