Repository Happyr/Doctrine-Specification, pull requests merged in 2019-11, with the labels that each got.

#231 Add a note on the repository trait
  docs/0-usage.md
Labels: feature

#234 Empty filter
  src/EntitySpecificationRepositoryTrait.php
  src/Logic/LogicX.php
Labels: bug

#235 Update master from 1.0
  docs/0-usage.md
  src/EntitySpecificationRepositoryTrait.php
  src/Logic/LogicX.php
Labels: bug

#236 Disable single_line_throw and no_superfluous_phpdoc_tags rules
  .php_cs.dist
  .styleci.yml
Labels: bug

#214 Add a deprecated comments and log messages for next major release
  docs/0-usage.md
  src/BaseSpecification.php
  src/Filter/Comparison.php
  src/Filter/In.php
  src/Logic/AndX.php
  src/Logic/LogicX.php
  src/Logic/OrX.php
  src/Operand/BitAnd.php
  src/Operand/BitLeftShift.php
  src/Operand/BitNot.php
  src/Operand/BitOr.php
  src/Operand/BitRightShift.php
  src/Operand/BitXor.php
  src/Operand/Bitwise.php
  src/Operand/PlatformFunction.php
  src/Query/AbstractSelect.php
  src/Query/GroupBy.php
  src/Query/Limit.php
  src/Query/Offset.php
  src/Query/OrderBy.php
  src/Query/QueryModifierCollection.php
  src/Result/ResultModifierCollection.php
  src/Spec.php
  src/Specification/Having.php
Labels: BC Break
